version: "3"

services:
  db:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  app:
    image: node:alpine
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
